"""Update pricing columns

Revision ID: 23c05e945670
Revises: 769e2703b202
Create Date: 2025-07-19 08:14:24.465686

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23c05e945670"
down_revision = "769e2703b202"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_business_id"), table_name="services")
    op.drop_constraint(
        op.f("services_business_id_fkey"), "services", type_="foreignkey"
    )
    op.drop_column("services", "business_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column("business_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("services_business_id_fkey"),
        "services",
        "businesses",
        ["business_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_services_business_id"), "services", ["business_id"], unique=False
    )
    # ### end Alembic commands ###
