"""add user id field to payment

Revision ID: 58916f4895c7
Revises: 9a425864bd5f
Create Date: 2025-07-19 12:10:45.225438

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '58916f4895c7'
down_revision = '9a425864bd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
