"""Update pricing columns

Revision ID: 769e2703b202
Revises: b80f2b556b86
Create Date: 2025-07-19 07:51:18.106987

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = "769e2703b202"
down_revision = "b80f2b556b86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column("pricing_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "services",
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "services",
        sa.Column("base_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "services",
        sa.Column("time_unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("services", sa.Column("min_duration", sa.Integer(), nullable=True))
    op.add_column("services", sa.Column("max_duration", sa.Integer(), nullable=True))
    op.add_column("services", sa.Column("pricing_tiers", sa.JSON(), nullable=True))
    op.drop_column("services", "pricing")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column(
            "pricing",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("services", "pricing_tiers")
    op.drop_column("services", "max_duration")
    op.drop_column("services", "min_duration")
    op.drop_column("services", "time_unit")
    op.drop_column("services", "base_price")
    op.drop_column("services", "currency")
    op.drop_column("services", "pricing_model")
    # ### end Alembic commands ###
