"""Update price fields

Revision ID: 79851bec6bf2
Revises: aedff726c796
Create Date: 2025-07-18 14:47:25.481395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '79851bec6bf2'
down_revision = 'aedff726c796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('bookings', 'total_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'total_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_column('bookings', 'currency')
    op.drop_column('bookings', 'base_price')
    # ### end Alembic commands ###
