"""Remove business

Revision ID: 7e9cd16e3009
Revises: 23c05e945670
Create Date: 2025-07-19 08:16:25.463905

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e9cd16e3009"
down_revision = "23c05e945670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
