"""support custom payments reference

Revision ID: 9a425864bd5f
Revises: abf759f199c4
Create Date: 2025-07-19 12:00:23.791671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9a425864bd5f'
down_revision = 'abf759f199c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('payments', sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('payments', 'booking_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_payments_reference_id'), 'payments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_payments_reference_type'), 'payments', ['reference_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_id'), table_name='payments')
    op.alter_column('payments', 'booking_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'reference_id')
    op.drop_column('payments', 'reference_type')
    # ### end Alembic commands ###
