"""remove currency column from booking

Revision ID: abf759f199c4
Revises: d501b8900f87
Create Date: 2025-07-19 10:45:26.958375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf759f199c4'
down_revision = 'd501b8900f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
