"""Fix service snapshot field

Revision ID: aedff726c796
Revises: f3f99de4c701
Create Date: 2025-07-18 08:09:40.071289

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "aedff726c796"
down_revision = "f3f99de4c701"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("service_snapshot", sa.JSON(), nullable=False))
    op.drop_column("bookings", "offering_snapshot")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("offering_snapshot", sqlite.JSON(), nullable=False)
    )
    op.drop_column("bookings", "service_snapshot")
    # ### end Alembic commands ###
