"""fix service model

Revision ID: b70e70a57d52
Revises: 10e33893c1cb
Create Date: 2025-07-19 08:33:53.441650

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b70e70a57d52"
down_revision = "10e33893c1cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
