"""Update payment model

Revision ID: b80f2b556b86
Revises: 84be562a014b
Create Date: 2025-07-18 15:35:00.389470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80f2b556b86'
down_revision = '84be562a014b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
