"""update payment method column

Revision ID: d501b8900f87
Revises: f8240686b191
Create Date: 2025-07-19 10:01:29.646798

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d501b8900f87"
down_revision = "f8240686b191"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column(
            "payment_method",
            sa.Enum("CARD", "MANDEL_COIN", name="paymentmethod"),
            nullable=False,
        ),
    )
    op.drop_column("payments", "method")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column(
            "method",
            postgresql.ENUM("CARD", "MANDEL_COIN", name="paymentmethod"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("payments", "payment_method")
    # ### end Alembic commands ###
